---
title: ""
toc: true
toc-depth: 1
toc-title: ""
---

# Pers en optredens

*"Schouten slaagt er in deze grillige, zoekende roman, vol filosofische overpeinzingen, wonderwel in om het schemergebied op te roepen waarin iemand leeft die chronisch pijn heeft"* - **de Volkskrant**

*"Dit boek wordt gedragen door Schoutens schrijfexperimenten"* - **De Standaard** (****)

*"Onbevreesd gooit Schouten haar literaire talent in de strijd. En dat leidt tot ijzersterke, poëtische beschrijvingen."* - **De Groene Amsterdammer** 

*"Nachtschade maakt indringend duidelijk hoe waanzinnige en terugkerende pijn je leven (ver)vormt"* - **NRC** (***)

- 17/11/2025 - **De Reactor** [recensie](https://www.dereactor.org/teksten/nachtschade-emma-laura-schouten)
- 29/10/2025 - **de lage landen | De Eerste Keer** [podcast](https://www.de-lage-landen.com/article/de-taal-waarmee-we-migraine-beschrijven-schiet-schromelijk-tekort-emma-laura-schouten-ontwikkelde-er-zelf-een-voor-nachtschade/)
- 12/10/2025 - **KAAP** [The writer is present](https://www.kaap.be/toont/writer-present-1-met-emma-laura-schouten-mariske-broeckmeyer)
- 11/10/2025 - **De Letterie** [Denkdag](https://www.uitinoostende.be/activiteiten/detail/20385/ons-ambigue-lijf-het-verhaal-van-een-lichaam-dat-wij-niet-verstaan-drie-denkdagen)
- 08/09/2025 - **Studio Migraine** [podcast](https://studio-migraine.nl/) met Ellen Terwindt
- 01/09/2025 - **Athenaeum | Scheltema** [leesfragment](https://athenaeumscheltema.nl/leesfragmenten/2025/nachtschade)
- 01/09/2025 - **Boekenkrant** [Shortlist Bronzen Uil 2025](https://boekenkrant.com/nieuws-shortlist-bronzen-uil-2025-bekend/)
- 29/07/2025 - **Vlaamse Pijnliga | Samana magazine** [interview](https://samana.be/magazine/migraine-auteur-emma-laura-schouten-breekt-een-lans-voor-meer-empathie-voor-onzichtbaar-lijden/)
- 17/07/2025 - **Nederlands Dagblad** [recensie](https://www.nd.nl/cultuur/boeken/1276365/migraine-virigina-woolf-susan-sontag-en-hildegard-von-bingen-)
- 12/06/2025 - **De Standaard** [best besproken titels van het afgelopen halfjaar](https://www.standaard.be/media-en-cultuur/boeken/op-zoek-naar-een-zomerboek-deze-titels-lazen-we-het-voorbije-halfjaar-het-liefst/71350797.html)
- 05/06/2025 - **Medisch Contact** [boekentip](https://www.medischcontact.nl/actueel/boeken-en-films/media-en-cultuur/nachtschade)
- 02/06/2025 - **de lage landen** [recensie](https://www.de-lage-landen.com/article/nachtschade-van-emma-laura-schouten-tussentijds-leven-met-een-beest-in-je-hoofd/) door Dirk Vandenberghe
- 01/06/2025 - **Literatuur en geneeskunde** [recensie](https://literatuurengeneeskunde.nl/scoop/) door Arko Oderwald
- 31/05/2025 - **De Morgen** boekentip
- 20/05/2025 - **NCRV-gids** [boekentip](https://www.ncrvgids.nl/leesclub/rouwdouwers-kijk-niet-om-de-kroon-met-twee-pieken-nachtschade/)
- 05/05/2025 - **Literair Nederland** [recensie](https://www.literairnederland.nl/recensie-emma-laura-schouten-nachtschade/) door Els van Swol
- 23/04/2025 - **De Standaard ** [20 boeken om te lezen op Vlaanderenleestdag](https://www.standaard.be/media-en-cultuur/boeken/20-boeken-om-te-lezen-op-vlaanderenleestdag/60531700.html)
- 18/04/2025 - **NRC** [recensie](https://www.nrc.nl/nieuws/2025/04/17/migraine-dwingt-complete-overgave-af-maakt-deze-debuutroman-indringend-duidelijk-a4890273) *** door Femke Brockhus
- 17/04/2025 - **Parool** signalement [nu ook in de boekhandel](https://www.parool.nl/kunst-media/nu-ook-in-de-boekhandel~b5d5801d/?referrer=https%3A%2F%2Fwww.google.com%2F)
- 09/04/2025 - **De Groene Amsterdammer** [recensie](https://www.groene.nl/artikel/soepel-meebewegen) door Sanne Bloemink
- 08/04/2025 - **Mappalibri** [recensie](https://mappalibri.be/?navigatieid=61&via_navigatieid=&recensieid=10814)
- 30/03/2025 - **de Volkskrant** [De 9 opmerkelijkste boeken van deze week](https://www.volkskrant.nl/cultuur-media/de-negen-opmerkelijkste-boeken-van-deze-week-foute-ouders-de-dikke-duce-en-voskuil-is-verliefd~b167bb37/)
- 28/03/2025 - **de Volkskrant** [recensie](https://www.volkskrant.nl/boeken/hoe-leer-je-leven-met-ondraaglijke-hoofdpijn-debuutroman-nachtschade-beschrijft-het-prachtig~b06b82ce/) door Maria van Dordrecht
- 28/03/2025 - **De Standaard** [De 10 beste boeken van maart 2025](https://www.standaard.be/media-en-cultuur/boeken/een-belgische-koningsdrama-of-levensadvies-van-een-betweter.-dit-zijn-de-tien-beste-boeken-van-maart-2025/51784400.html)
- 21/03/2025 - **Hoofdpijnnet** Hoofdzaken [recensie](https://drive.google.com/file/d/1iv1orZhiXCKgeEnQMKocInon6l-XtFe9/view?usp=drive_link)
- 18/03/2025 - **ILFU** [21 debutanten van deze lente die opvielen](https://ilfu.com/alle-artikelen/de-21-voorjaarsdebuten-van-2025)
- 18/03/2025 - **Irma Driessen / imhd.nl** [recensie](https://www.imhd.nl/log/nachtschade-2/)
- 15/03/2025 - **just read** [recensie](https://www.justread.nl/fictie/emma-laura-schouten-nachtschade/#more-4180)
- 14/03/2025 - **Editio** [interview](https://www.editio.nl/magazine/verdieping/nachtschade-zoektocht-naar-taal-voor-pijn.html)
- 08/03/2025 - **De Standaard** [interview](https://www.standaard.be/cnt/dmf20250307_96038863)
- 08/03/2025 - **Sintel Tijdschrift** [boekentip](https://www.sinteltijdschrift.nl/2025/03/08/debuutroman-nachtschade/#:~:text=In%20het%20komende%20nummer%20van,de%20Belgische%20krant%20De%20Standaard.)
- 01/03/2025 - **De Standaard** [recensie](https://www.standaard.be/cnt/dmf20250227_96331906) **** door Lodewijk Verduin
- 28/02/2025 - **care4migraine** [ervaringsverhaal](https://care4migraine.nl/ervaringsverhalen/mijn-migraine-toen-nu-en-straks-emma-schouten-vertelt)
- 24/02/2025 - **NPO Radio 4 Opium** [talent van de week](https://www.npoklassiek.nl/fragmenten/opium/9e4c1dff-5278-4d5b-981b-16f271ea583a/2025-02-25-het-talent-emma-laura-schouten)
- 24/02/2025 - **Marieke Groen** [blog](https://mariekegroen.blogspot.com/2025/02/een-club-waar-je-niet-bij-wil-horen.html)
- 24/02/2025 - **Vrouwenbibliotheek Utrecht** boekentip [nieuwsbrief maart](https://vrouwenbibliotheek.nl/2025/02/25/maart-nieuwsbrief-6/)
- 15/02/2025 - **Editio** nieuwsbrief
- 14/02/2025 - **ELLE** magazine 2025-1 boekentip
- 14/02/2025 - **Hoofd_stuk.be** boekentip
- 13/02/2025 - **LINDA.** #248 boekentip
- 13/02/2025 - **OBA** [boekpresentatie](https://www.oba.nl/agenda/oosterdok/boekpresentatienachtschade.html)
- 06/01/2025 - **De Standaard** [15 tips voor een literair voorjaar](https://www.standaard.be/cnt/dmf20250105_96779139)
- 18/10/2024 - **deBuren** [Nieuw Geluid](https://deburen.eu/magazine/nachtschade#:~:text=Op%2018%20oktober%20stelden%20de,taal%20en%20denken%20elkaar%20be%C3%AFnvloeden)
