---
title: ""
toc: true
toc-depth: 1
toc-title: ""
---

# Portfolio

## 2026

### Publicaties
- **Shortreads_**: [Poëzie en korte verhalen](https://shortreads.nl/auteur/emmalauras/) 

### Optredens en projecten

- 19 mei: **IAS** [Pain Imagined, Embodied, Told: A Polyphonic Encounter Between Art, Science and Care](https://ias.uva.nl/content/events/2026/05/pain-imagined-embodied-told-a-polyphonic-encounter-between-art-science-and-care.html), UvA UB
- 7 & 8 maart: **FAAR Oostende** [Sofagesprek & leesclub](https://www.faar-oostende.be/auteurs/emma-laura-schouten)
- 12 februari: **Libris x boekhandel Van der Velde** (Zwolle)  [Tussen longlist en shortlist](https://www.vanderveldeboeken.nl/agenda-zwolle/12-02-libris-literatuur-prijs-tussen-longlist-en-shortlist-2026)
- **We moeten het over literatuur hebben** [interview](https://www.youtube.com/watch?v=uxkpSfsKwks) met Amedeo Durnez
- **Decamerone** dichtersgezelschap
- **OBA** Schrijfwerkplaats

## 2025

### Publicaties
- **De Heg** - Samengesteld door Naomi Jansen [poëzie]: *Limes* & *De gluurder, de schepper*
- **Voices for Women** [essay]: [*Tussen ziek en gezond: De hiërarchie van ziektes*](https://voicesforwomen.nl/blog/tussen-ziek-en-gezond-de-hierarchie-van-ziektes/) (eerder gepubliceerd door Uitgeverij HetMoet)
- **Sintel** [kort verhaal]: *Cariës*
- **Shortreads_**: [Poëzie en korte verhalen](https://shortreads.nl/auteur/emmalauras/) 

### Optredens en projecten
- **De Bronzen Uil** prijsuitreiking-festival: vertoning kortfilm 'Reis door de tussentijd'
- 12/10/2025 - **KAAP** [The writer is present](https://www.kaap.be/toont/writer-present-1-met-emma-laura-schouten-mariske-broeckmeyer)
- **De Letterie** [Denkdag](https://www.uitinoostende.be/activiteiten/detail/20385/ons-ambigue-lijf-het-verhaal-van-een-lichaam-dat-wij-niet-verstaan-drie-denkdagen)
- **de lage landen | De Eerste Keer** [podcast](https://www.de-lage-landen.com/article/de-taal-waarmee-we-migraine-beschrijven-schiet-schromelijk-tekort-emma-laura-schouten-ontwikkelde-er-zelf-een-voor-nachtschade/)
- **Studio Migraine** [podcast](https://studio-migraine.nl/) met Ellen Terwindt
- 24/02/2025 - **NPO Radio 4 Opium** [talent van de week](https://www.npoklassiek.nl/fragmenten/opium/9e4c1dff-5278-4d5b-981b-16f271ea583a/2025-02-25-het-talent-emma-laura-schouten)
- **De Buurtkringloop** Amsterdam-Oost commissie openingsfeest nieuwe winkel
- **Editio** Jurylid Debutantenwedstrijd
- **Marineterrein Amsterdam** - De Heg: voordracht finissage Gluursculptuur
- **OBA** Schrijfwerkplaats

## 2024

### Publicaties
- **Melopee Poëzieprijs 2024** bloemlezing genomineerde gedichten: *Voorland* (uit Het Liegend Konijn 2023-1)
- **Sintel** [Poëzie]: *Maleficiën*, *Noorderzon*, *Cesuur*, *Grativatielens*, *Mitose*
- **Shortreads_**: [Poëzie en korte verhalen](https://shortreads.nl/auteur/emmalauras/) 
- **Pelckmans Uitgevers** Poëzieagenda 2024: *De nacht dat het water kwam* (uit Het Liegend Konijn 2023-1)

### Optredens en projecten
- **OBA** Schrijfwerkplaats
- **deBuren** [talentontwikkeltraject Nieuw Geluid](https://deburen.eu/magazine/nachtschade)
- **Debutantenbal** Workshop 'Feedback op je verhaal'
- **Editio** Jurylid Debutantenwedstrijd
- **Haarlems Studenten Koor** muzikaal-literair project 'Niemandsland'
- **Sintel Tijdschrift** presentatie Sintel #8

## 2023

### Publicaties
- **Uitgeverij HetMoet** [Essay]: [*Tussen ziek en gezond: De hiërarchie van ziektes*](https://www.hetmoet.com/post-1/tussen-ziek-en-gezond-de-hi%C3%ABrarchie-van-ziektes) in de bundel [*Vreselijk verlangen*](https://www.hetmoet.com/product-page/vreselijk-verlangen-een-verzameling-smachtende-mammoetjes)
- **The New Menard Press** [Essay]: [*Between Sickness and Health: the Hierarchy of Illnesses*](https://www.thenewmenardpress.com/post/between-sickness-and-health-the-hierarchy-of-illnesses) (translation)
- **The Galaxy Gazette** [Poëzie]: *Homunculus*
- **Kluger Hans** [Poëzie]: *efedea* 
- **Het Liegend Konijn** [Poëzie]: *Nachtschade*, *Midzomerhymne*, *Hic sunt dracones*, *De nacht dat het water kwam*, *Voorland*
- **Op Ruwe Planken** [Poëzie]: *Halewijn* 
- **Tijdschrift Landauer** [Poëzie]: [*Wachters op de morgen*, *Weefselleer*, *Uitdrijving*](https://tijdschriftlandauer.nl/poezie/emma-laura-schouten/)

### Optredens en projecten
- **Kunstweek Warmond** Poëzie in de Oranjerie
- **Dichters van de Prinsentuin**
- **Marineterrein Amsterdam** kunstproject ParkxPark - De Heg 
- **The Writer's Guide to the Galaxy** presentatie *The Galaxy Gazette* #2 
- **Notes of a dirty old man** Bar Bukowski
- **5 mei Vrijheidsmaaltijd** Deventer
- **The Writer's Guide to the Galaxy** A mic of one's own 

## 2022

### Publicaties
- **Seizoenszine** [Poëzie]: *Er zijn zij die zeggen de herfst begint* (2022)
- **Tijdschrift Ei** [Poëzie]: *Sisyfus* (2022) 
- Bloemlezing **Met het oog op Gorssel** [Poëzie]: *Discours*, *Fantoompijn* (2022)
- **Vuurland** [Recensie]: recensie [*Wormmaan*](https://www.vuurland.nu/post/1782)
- **Seizoenszine** [Poëzie]: *Fotosynthese* (2022)
- **Hard//hoofd** [Essay]: [*De schrijver mag schrijven, de lezer mag lezen*](https://hardhoofd.com/de-schrijver-mag-schrijven-de-lezer-mag-lezen/), [*Lang leve de slush pile*](https://hardhoofd.com/lang-leve-de-slush-pile/), [*Hadden we dat altijd maar geweten*](https://hardhoofd.com/hadden-we-dat-altijd-maar-geweten/) (2022)

### Optredens en projecten
- **Op de Schans**
- **ROEM** schrijfresidentie
- **Uitgeverij HetMoet** ZeilSchrijfZomerCursus
- **Tapschrift Amsterdam** 
- **Seizoenszine** presentatie Theater De Nieuwe Vorst
- **Editio** jurylid fictie Debutantenschrijfwedstrijd
